INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (1,'R8Z 3F6','eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer','Halla Wong',6639);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (2,'K9C 5G8','in,','Sara Gentry',3158);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (3,'N4E 8V0','molestie sodales. Mauris blandit enim consequat purus. Maecenas libero','Benjamin Frederick',3297);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (4,'U7J 8G1','nec urna suscipit nonummy.','Rhoda Melendez',344);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (5,'F2Y 0U0','aliquam eu, accumsan sed,','Price Baker',9198);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (6,'H3N 9N1','at, velit. Cras lorem lorem, luctus ut, pellentesque','Amela Estes',3641);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (7,'T3U 7M5','eu, ligula. Aenean','Suki Diaz',4604);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (8,'X9Z 4T8','pellentesque, tellus sem','Eugenia Collier',2060);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (9,'T0A 6X5','tellus eu augue porttitor interdum. Sed auctor odio','Macy Bolton',2263);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (10,'O5O 9S6','facilisis','Linus Foreman',8306);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (11,'I4L 9O2','dolor','Oliver Prince',1235);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (12,'I6A 4B3','ut, pellentesque eget, dictum placerat,','Kessie Hodge',1457);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (13,'G9L 6U5','molestie arcu. Sed','Tatum Jordan',8710);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (14,'P8H 3W4','blandit mattis. Cras eget nisi dictum augue malesuada','Ora Gentry',4712);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (15,'M1L 1C2','massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet','Alana Freeman',1870);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (16,'R1B 0O0','amet','Isabella Kinney',1822);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (17,'G0A 4V9','Cum sociis natoque','Tyrone Sloan',8206);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (18,'Y5L 3W1','nec, cursus a, enim. Suspendisse aliquet, sem','Micah Castro',1713);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (19,'K9B 5Y1','diam dictum sapien. Aenean','Chaney Barrera',4967);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (20,'B3S 0W1','sit amet metus. Aliquam erat volutpat. Nulla facilisis.','Anastasia Holman',6230);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (21,'I5T 2R1','penatibus et magnis dis','Virginia Berry',9050);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (22,'M9T 9M5','aliquam eros','Mari Howell',4008);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (23,'Z5N 3Z5','urna et arcu','Allegra Knight',1671);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (24,'E9Q 0O5','conubia nostra, per inceptos hymenaeos. Mauris ut','Ivy Short',1026);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (25,'A0A 1C1','diam lorem,','Rashad Clements',6811);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (26,'T1W 4K5','fermentum risus, at fringilla','Sylvester Robbins',5454);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (27,'V0A 0C7','non, cursus non, egestas a, dui. Cras pellentesque. Sed','Xenos Casey',9805);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (28,'N2B 6Q0','In faucibus. Morbi','Ruth Mitchell',9874);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (29,'H4T 9T9','Sed eget lacus. Mauris non','Shelley Marquez',2631);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (30,'P7J 8N9','sed orci lobortis augue scelerisque mollis. Phasellus','Griffin Bolton',4070);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (31,'I4E 1V8','Nulla dignissim. Maecenas ornare egestas ligula. Nullam','Kenyon Bradley',9680);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (32,'T7H 6W6','molestie. Sed id risus quis diam luctus lobortis.','Daphne Goodwin',5429);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (33,'A4E 1O6','Cras dolor dolor, tempus non, lacinia at,','Quintessa Gillespie',7660);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (34,'V1Z 7V2','feugiat placerat velit.','Frances Campbell',9822);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (35,'G5J 7T5','in felis. Nulla tempor','Ulric Matthews',984);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (36,'C7W 5S9','nec, eleifend non, dapibus rutrum,','Xander Harrison',1481);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (37,'T9F 5W1','adipiscing non, luctus sit amet, faucibus ut, nulla.','Dante Villarreal',2621);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (38,'Q4N 2Q7','netus et malesuada fames ac','Dylan Miranda',6537);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (39,'D3F 6M7','erat eget ipsum. Suspendisse sagittis.','Rina Erickson',7088);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (40,'N7X 2I5','orci','Charde Welch',201);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (41,'U4C 0H6','sed dictum eleifend, nunc risus','Rigel Daniels',7335);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (42,'B9M 1L5','a, magna.','Byron Cochran',7800);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (43,'N3I 7Q9','non, hendrerit','Ulysses Riggs',6662);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (44,'I0T 4O0','tincidunt pede ac urna.','Inez Bruce',8044);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (45,'S9X 2A8','augue eu tellus. Phasellus elit pede, malesuada vel, venenatis','Damian Lambert',6656);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (46,'Z2U 6S0','ornare, lectus ante dictum mi, ac','Laith Daniel',4073);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (47,'T8Z 0S1','senectus et netus et malesuada fames ac','Kyle Osborne',6881);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (48,'E5L 4B6','primis in faucibus orci luctus et ultrices posuere','Jillian Oneil',6963);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (49,'C3R 7J4','vulputate velit eu sem. Pellentesque','Ahmed Smith',7899);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (50,'K9Q 8D7','consectetuer','Vielka Leach',4935);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (51,'J6W 7P2','quis, pede. Suspendisse dui. Fusce','Aiko Nicholson',4950);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (52,'R4B 7B5','at augue id ante dictum cursus. Nunc','Maggy Lowery',759);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (53,'A0W 2A1','nascetur ridiculus','Baker Stark',845);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (54,'X9N 8J3','orci. Donec nibh.','TaShya Wheeler',7553);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (55,'Z1R 6M2','aliquet, sem ut cursus luctus, ipsum leo','Burton Ingram',6440);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (56,'O6G 7Q6','Duis gravida. Praesent eu nulla at','Scarlett Mendez',268);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (57,'E4E 3V4','quam a felis ullamcorper viverra. Maecenas iaculis aliquet','Keely Castaneda',7340);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (58,'I3F 1E8','lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor','Jackson Trevino',5527);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (59,'E0H 4S8','sapien. Cras dolor dolor, tempus non, lacinia at,','Howard Dickerson',7721);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (60,'W9L 4W1','ac sem ut dolor dapibus gravida. Aliquam','Kim Camacho',5810);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (61,'M9H 7M4','elit,','Rudyard Wright',7143);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (62,'D6Y 3U5','Fusce dolor quam, elementum at, egestas a,','Diana Carrillo',3446);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (63,'Q5V 3Z4','cursus in,','Mona Blanchard',2298);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (64,'F7O 4A8','massa lobortis ultrices. Vivamus rhoncus. Donec','Kieran Marshall',8740);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (65,'O5F 3F9','adipiscing elit. Etiam','Evan Montgomery',2278);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (66,'H6H 0U7','fringilla. Donec feugiat metus sit amet ante. Vivamus non','Daria Sloan',7089);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (67,'A6X 8U6','Maecenas','Renee Kirk',6371);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (68,'Y4A 5U5','malesuada','Ursa Bush',4549);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (69,'W9H 4D3','nisl. Maecenas malesuada fringilla','Aline Hanson',5926);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (70,'S4M 1K6','fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh','Boris Turner',9822);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (71,'B9F 1Z0','dapibus quam quis','Carson Cain',9180);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (72,'V3O 9G4','nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis.','Byron Bowman',4414);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (73,'H6V 8N8','In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus.','Kiona Daniel',262);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (74,'I7L 5Y1','urna','Clio Henderson',9259);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (75,'C9A 4K4','Donec fringilla. Donec feugiat metus sit','Logan Cruz',1699);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (76,'A3V 3P3','Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac,','Coby Byers',9794);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (77,'C3Z 5V2','consequat','Erin Warner',9546);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (78,'O3K 2I2','Suspendisse dui. Fusce diam nunc,','Chiquita Mckee',1843);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (79,'V6A 5U3','odio. Etiam ligula','Elaine Gordon',3081);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (80,'B0Q 0B6','elit, a feugiat tellus lorem eu metus. In','Lesley Newton',4896);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (81,'Z5B 4W5','non arcu. Vivamus','Farrah Quinn',8325);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (82,'B2X 8Z7','vitae odio sagittis semper. Nam tempor diam','Hyacinth Boyle',4761);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (83,'S3P 9V0','justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate,','Erasmus Mckay',8982);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (84,'R9M 9T8','pretium neque.','Elizabeth Weiss',3151);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (85,'Q0B 0R5','egestas. Aliquam fringilla cursus','Cyrus Todd',1469);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (86,'N5S 3V8','est, congue a, aliquet','Kaden Ochoa',4984);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (87,'H8B 2J6','eu, euismod','Nissim Gregory',5921);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (88,'I2B 4W1','Proin','Taylor Suarez',895);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (89,'T7G 1O9','aliquam adipiscing lacus.','Cullen Clay',4175);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (90,'U0I 2Q7','eu enim. Etiam','Cadman Bates',7128);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (91,'A9D 6R0','lorem eu','Elizabeth Roman',9479);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (92,'N1V 4L3','ligula. Aenean gravida nunc sed pede. Cum sociis','Sasha Pollard',7542);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (93,'G1L 9Y2','ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo','Stone Travis',9107);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (94,'X3L 2K4','Mauris nulla. Integer urna.','Bethany Reese',9847);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (95,'R7E 9K4','mollis nec, cursus a, enim. Suspendisse aliquet, sem ut','Xerxes Hubbard',5324);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (96,'T0E 5J0','non massa non','Elijah Oneil',1605);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (97,'S3A 2Z0','molestie sodales. Mauris','Dexter Waller',140);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (98,'M5T 1M6','arcu','Denton Carlson',6781);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (99,'O0Y 2B7','mauris. Integer sem','Shay Jacobs',45);
INSERT INTO product (ID,COD_BARRA,DESCRIPTION,NAME,VALUE) VALUES (100,'E2T 3C6','nulla. Cras','Jamalia Roach',57);